/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Circleid = number;
export type Name = string;
export type Author = string;
export type Isreject = boolean;
export type Hall = "東" | "南" | "西";
export type Day = "土" | "日";
export type Block = string;
export type Space = string;
export type Haichistr = string;
export type Is2Sp = boolean;
export type Ismain = boolean;
export type Loc = number;
export type Genre = string;
export type Circlecuturls = string[];
export type Webcirclecuturls = string[];
export type Moviecuturls = (string | null)[];
export type Id1 = string;
export type Officialcircleid = number;
export type Thumbnailurl = string;
export type Bigimageurl = string;
export type R18 = boolean;
export type Imagecode = number;
export type Updatedat = number;
export type Isnew = boolean;
export type Isonlinebooksregistered = boolean;
export type Ispixivregistered = boolean;
export type Pixivurl = string;
export type Istwitterregistered = boolean;
export type Twitterurl = string;
export type Isniconicoregistered = boolean;
export type Niconicourl = string;
export type Isclipstudioregistered = boolean;
export type Clipstudiourl = string;
export type Haskokutiimage = boolean;
export type Hashanpuimage = boolean;
export type Website = string;
export type Cancashless = boolean;
export type Cashlesstypes = string;
export type Description = string;

export interface Circle {
  Id: Id;
  CircleId: Circleid;
  Name: Name;
  Author: Author;
  IsReject: Isreject;
  Hall: Hall;
  Day: Day;
  Block: Block;
  Space: Space;
  HaichiStr: Haichistr;
  Is2SP: Is2Sp;
  IsMain: Ismain;
  Loc: Loc;
  Genre: Genre;
  CircleCutUrls: Circlecuturls;
  WebCircleCutUrls: Webcirclecuturls;
  MovieCutUrls: Moviecuturls;
  Image1: Image | null;
  Image2: Image | null;
  BookImage: Image | null;
  IsNew: Isnew;
  IsOnlineBooksRegistered: Isonlinebooksregistered;
  IsPixivRegistered: Ispixivregistered;
  PixivUrl: Pixivurl;
  IsTwitterRegistered: Istwitterregistered;
  TwitterUrl: Twitterurl;
  IsNiconicoRegistered: Isniconicoregistered;
  NiconicoUrl: Niconicourl;
  IsClipstudioRegistered: Isclipstudioregistered;
  ClipstudioUrl: Clipstudiourl;
  HasKokutiImage: Haskokutiimage;
  HasHanpuImage: Hashanpuimage;
  WebSite: Website;
  CanCashless: Cancashless;
  CashlessTypes: Cashlesstypes;
  Description: Description;
  [k: string]: unknown;
}
export interface Image {
  Id: Id1;
  OfficialCircleId: Officialcircleid;
  ThumbnailUrl: Thumbnailurl;
  BigimageUrl: Bigimageurl;
  R18: R18;
  imageCode: Imagecode;
  UpdatedAt: Updatedat;
  [k: string]: unknown;
}
